project_name: receptionist
before:
  hooks:
    - pkger
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.appVersion={{ .Version }}
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "cuotos/{{ .ProjectName }}:{{ .Tag }}"
      - "cuotos/{{ .ProjectName }}:v{{ .Major }}"
      - "cuotos/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "cuotos/{{ .ProjectName }}:latest"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
